kind: template
load: nodeProject.jsonnet
data:
  config: |
    {
        "docker": {
            "host": "chronos.dasred.de",
            "port": 7770,
            "labels": {
                "grafana.display": true,
                "grafana.name": "marco-starker.de",
                "homeassistant.enable": true,
                "homeassistant.device_name": "marco-starker.de"
            }
        }
    }
