import 'bootstrap';
import animation from './animation.js';
import contact from './contact.js';
import navAndLink from './navAndLink.js';
import project from './project.js';
import service from './service.js';
import shakyBoxes from './shakyBoxes.js';
import skill from './skill.js';
import testimonial from './testimonial.js';
import typewriter from './typewriter.js';

navAndLink();
typewriter();
service();
testimonial();
skill();
animation();
shakyBoxes();
project();
contact();